#!/bin/sh

if test ! $# = 2
then
    echo "Têm que inserir 2 argumentos"

else
    if test ! -d $1
    then
	echo "O 1º argumento tem que ser um directorio"

else
	echo > `basename $1`.tams

	for i in $1/*.$2
	do
	    echo `wc -c $i` >> `basename $1`.tams
	done
    fi
fi

    